### ISSUE TITLE
Condition for GitHub release (full/pre) is not working correctly

### ISSUE THREAD

**Issue by tomkerkhove** [arcus-azure/azure-devops-templates#29]
**Describe the bug**
Condition for GitHub release (full/pre) is not working correctly.

Example: https://dev.azure.com/codit/Arcus/_build/results?buildId=41053&view=results

**To Reproduce**
- Release Messaging preview

**Expected behavior**
Preview release

**Actual behavior**
Full release

**Comment by stijnmoreels** [comment]
The template `github/create-pre-release.yml` contains a template parameter `tag` that has as default value `v$(Build.BuildNumber)`.

The expansion of the variable (`v$(Build.BuildNumber` to `v0.1.0-preview-2`) happens correcty for the GitHub release task, but not for the condition => resulting in a `false` outcome and having a full release instead of a pre-release.

The official docs states that variable expansion on task conditions happens before the condition is being evaluated, but in this case; the expansion has to happen twice.
Not sure if that's the problem, or that we in a template. Setting the default value in the first task (the bash script task to check for required parameters), instead of directly in the template parameter seems like an option.

**Comment by tomkerkhove** [comment]
> Not sure if that's the problem, or that we in a template. Setting the default value in the first task (the bash script task to check for required parameters), instead of directly in the template parameter seems like an option.

So what I'm hearing is that the default value is basically the issue. In that case, I would remove the default indeed and enforce it to be specified.

That's actually also better, maybe, since it's more explicit on the "consumer" side to explicitly list what the tag is that will be used. Thoughts?

**Comment by stijnmoreels** [comment]
> > Not sure if that's the problem, or that we in a template. Setting the default value in the first task (the bash script task to check for required parameters), instead of directly in the template parameter seems like an option.
> 
> So what I'm hearing is that the default value is basically the issue. In that case, I would remove the default indeed and enforce it to be specified.
> 
> That's actually also better, maybe, since it's more explicit on the "consumer" side to explicitly list what the tag is that will be used. Thoughts?

Yes, I can live with that! We don't have any 'versions' of the templates, so we have to change each repo first to use it explicitly. I guess.

But again. That's my best guess on the problem. I'm not sure how to test this. It's maybe an option to add also a release YAML in this repo and release dummy GitHub releases here? Or is that too much?

**Comment by tomkerkhove** [comment]
Certainly not overkill, but maybe we create a dummy project for it?

**Comment by stijnmoreels** [comment]
> Certainly not overkill, but maybe we create a dummy project for it?

You mean like some source code? Because that's already here, no?

**Comment by tomkerkhove** [comment]
No, a GitHub repo to create the releases on so that this one is not getting polluted.

For example, `arcus-azure/azure-devops-templates-tests`

**Comment by stijnmoreels** [comment]
> No, a GitHub repo to create the releases on so that this one is not getting polluted.
> 
> For example, `arcus-azure/azure-devops-templates-tests`

Ah, yes. just an empty repo with test releases.

**Comment by stijnmoreels** [comment]
Created: #30

**Comment by tomkerkhove** [comment]
Had same issue with background jobs again.
